# vim:ft=ansible:
- hosts: all
  become: yes
  connection: local
  roles:
    - python
    - franklinkim.users-oh-my-zsh
    - powerline
    - vim
    - docker-debian
  tasks:
    - name: append GO bin directory to path
      lineinfile: dest=/home/{{ vim_users }}/.zshrc line="export PATH=$PATH:/usr/local/go/bin"
    - name: add GO work directory
      lineinfile: dest=/home/{{ vim_users }}/.zshrc line="export GOPATH=/home/simmol/projects/go"
    - name: add GOCD command
        lineinfile: dest=/home/{{ vim_users }}/.zshrc line="gocd () { cd `go list -f '{{.Dir}}' $1` }"
    - name: Make projects directory
      file: path=/home/{{ vim_users }}/Projects state=directory owner="{{ vim_users }}" group="{{ vim_users }}"
  vars:
    vim_users: simmol
    vim_package: vim
    vim_plugins:
      - "scrooloose/nerdtree"
      - "jistr/vim-nerdtree-tabs"
      - "tpope/vim-fugitive"
      - "klen/python-mode"
      - "fatih/vim-go"
      - "Shougo/neocomplete"
      - "weynhamz/vim-plugin-minibufexpl"
      - "vim-scripts/indentpython.vim"
      - "scrooloose/syntastic"
    vim_custom_config_file: ~
    users:
      - name: simmol
        username: simmol
        authorized_keys: []
        oh_my_zsh:
          theme: agnoster
