# vim:ft=ansible:
- hosts: all
  become: yes
  connection: local
  roles: 
    - python
    - franklinkim.users-oh-my-zsh
    - powerline
    - vim
  tasks:
    - name: append GO directory to path
      lineinfile: dest=/home/{{ vim_users }}/.zshrc line="export PATH=$PATH:/usr/local/go/bin"
    - name: add GO work directory
      lineinfile: dest=/home/{{ vim_users }}/.zshrc line="export GOPATH=/home/simmol/projects/go"
  vars:
    vim_users: simmol
    vim_package: vim 
    vim_plugins:
      - "scrooloose/nerdtree"
      - "tpope/vim-fugitive"
      - "klen/python-mode"
      - "fatih/vim-go"
      - "Shougo/neocomplete"
      - "weynhamz/vim-plugin-minibufexpl"
      #      - "Valloric/YouCompleteMe"
    vim_custom_config_file: ~
    users:
      - name: simmol
        username: simmol
        authorized_keys: []
        oh_my_zsh:
          theme: agnoster
