---

- name: Install python 2.7 related packages
  become: yes
  apt: "name={{item}} state=installed"
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-pip

- name: Upgrade Pip to lattest version
  become: yes
  pip: name="pip" state="latest"

- name: Install Virtualenv
  become: yes
  pip: name="virtualenv"

- name: Install Virtualenvwrapper
  become: yes
  pip: name="virtualenvwrapper"
